name: Docker_Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker Build For employee Management Microservice
      run: |
        Docker build ./employeeDetailsService -t wathsara/employee-microservice:1.0.0
